### ISSUE TITLE
AttributeError: 'QColorEdit' object has no attribute 'colorEdit'

### ISSUE THREAD

**Issue by sdothum** [ShadowKyogre/slickpicker#2]
Get the following..

`Traceback (most recent call last):`
`  File "/usr/bin/slickpicker", line 11, in <module>`
`    print(picker.colorEdit.text())`
`AttributeError: 'QColorEdit' object has no attribute 'colorEdit'`
`QObject::startTimer: QTimer can only be used with threads started with QThread`

I am assuming slickpicker is supposed to print out the "picked" hex color value (that is what I am hoping it does!)

**Comment by ShadowKyogre** [comment]
Fixed it! Try running it again and it'll print the color out on the commandline output on exit.
